name: vandenrobotics
favicon: null
layout_spectrum: 0.0659983647055924
typography_spectrum: 0.11658612382598221
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.23264658055268228
  lightness: 0.980957506224513
  saturation: 0.09268460306338966
  rhythmicContrast: 0.8496080082841218
purpose: []
