name: vandenrobotics
favicon: null
layout_spectrum: 0.3392
typography_spectrum: 0.63929
title: Vanden Robotics
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-47450110-6
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#004800'
    - '#808080'
    - '#e3b104'
  brandStrength: 0.5
  lightness: 0.1875
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
