name: vandenrobotics
favicon: null
layout_spectrum: 0.3392
typography_spectrum: 0.14877
title: Vanden Robotics
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-47450110-6
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e3b104'
    - '#004800'
    - '#808080'
    - '#928968'
    - '#386038'
  brandStrength: 1
  lightness: 0
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
